spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver  
      username: root 
      password: root
      url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
  rabbitmq:
    host: 192.168.10.67
    port: 5672
    password: admin
    username: admin    
env: dev
server:
  port: 8083
