spring:
  application:
    name: order
  datasource:
      driver-class-name: com.mysql.jdbc.Driver  
      username: root 
      password: root
      url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.67:8761/eureka/   
      
env: test

server:
  port: 8081
