spring:
  application:
    name: product
  datasource:
      driver-class-name: com.mysql.jdbc.Driver  
      username: root 
      password: root
      url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest      
      
env: dev

server:
  port: 8082
girl:
  name: lili2
  age: 199
