spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver  
      username: root 
      password: root
      url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
